/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as KnowledgeGraphImport } from './routes/knowledge-graph'
import { Route as IndexImport } from './routes/index'
import { Route as NewsFeedIndexImport } from './routes/news-feed.index'
import { Route as NewsFeedDocumentidImport } from './routes/news-feed.$documentid'

// Create/Update Routes

const KnowledgeGraphRoute = KnowledgeGraphImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NewsFeedIndexRoute = NewsFeedIndexImport.update({
  id: '/news-feed/',
  path: '/news-feed/',
  getParentRoute: () => rootRoute,
} as any)

const NewsFeedDocumentidRoute = NewsFeedDocumentidImport.update({
  id: '/news-feed/$documentid',
  path: '/news-feed/$documentid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphImport
      parentRoute: typeof rootRoute
    }
    '/news-feed/$documentid': {
      id: '/news-feed/$documentid'
      path: '/news-feed/$documentid'
      fullPath: '/news-feed/$documentid'
      preLoaderRoute: typeof NewsFeedDocumentidImport
      parentRoute: typeof rootRoute
    }
    '/news-feed/': {
      id: '/news-feed/'
      path: '/news-feed'
      fullPath: '/news-feed'
      preLoaderRoute: typeof NewsFeedIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/news-feed/$documentid': typeof NewsFeedDocumentidRoute
  '/news-feed': typeof NewsFeedIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/news-feed/$documentid': typeof NewsFeedDocumentidRoute
  '/news-feed': typeof NewsFeedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/news-feed/$documentid': typeof NewsFeedDocumentidRoute
  '/news-feed/': typeof NewsFeedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/knowledge-graph' | '/news-feed/$documentid' | '/news-feed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/knowledge-graph' | '/news-feed/$documentid' | '/news-feed'
  id:
    | '__root__'
    | '/'
    | '/knowledge-graph'
    | '/news-feed/$documentid'
    | '/news-feed/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  NewsFeedDocumentidRoute: typeof NewsFeedDocumentidRoute
  NewsFeedIndexRoute: typeof NewsFeedIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  NewsFeedDocumentidRoute: NewsFeedDocumentidRoute,
  NewsFeedIndexRoute: NewsFeedIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/knowledge-graph",
        "/news-feed/$documentid",
        "/news-feed/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/knowledge-graph": {
      "filePath": "knowledge-graph.tsx"
    },
    "/news-feed/$documentid": {
      "filePath": "news-feed.$documentid.tsx"
    },
    "/news-feed/": {
      "filePath": "news-feed.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
