/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ImporterImport } from './routes/importer'
import { Route as FeedImport } from './routes/feed'
import { Route as IndexImport } from './routes/index'
import { Route as SearchIndexImport } from './routes/search.index'
import { Route as NewsFeedIndexImport } from './routes/news-feed.index'
import { Route as KnowledgeGraphIndexImport } from './routes/knowledge-graph.index'
import { Route as InsightStudioIndexImport } from './routes/insight-studio.index'
import { Route as NewsFeedDocumentidImport } from './routes/news-feed.$documentid'
import { Route as InsightInsightIdImport } from './routes/insight.$insightId'
import { Route as InsightStudioInsightIdImport } from './routes/insight-studio.$insightId'
import { Route as GuestFeedImport } from './routes/guest.feed'
import { Route as KnowledgeGraphGraphTypeDocumentidImport } from './routes/knowledge-graph.$graphType.$documentid'

// Create/Update Routes

const ImporterRoute = ImporterImport.update({
  id: '/importer',
  path: '/importer',
  getParentRoute: () => rootRoute,
} as any)

const FeedRoute = FeedImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SearchIndexRoute = SearchIndexImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any)

const NewsFeedIndexRoute = NewsFeedIndexImport.update({
  id: '/news-feed/',
  path: '/news-feed/',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeGraphIndexRoute = KnowledgeGraphIndexImport.update({
  id: '/knowledge-graph/',
  path: '/knowledge-graph/',
  getParentRoute: () => rootRoute,
} as any)

const InsightStudioIndexRoute = InsightStudioIndexImport.update({
  id: '/insight-studio/',
  path: '/insight-studio/',
  getParentRoute: () => rootRoute,
} as any)

const NewsFeedDocumentidRoute = NewsFeedDocumentidImport.update({
  id: '/news-feed/$documentid',
  path: '/news-feed/$documentid',
  getParentRoute: () => rootRoute,
} as any)

const InsightInsightIdRoute = InsightInsightIdImport.update({
  id: '/insight/$insightId',
  path: '/insight/$insightId',
  getParentRoute: () => rootRoute,
} as any)

const InsightStudioInsightIdRoute = InsightStudioInsightIdImport.update({
  id: '/insight-studio/$insightId',
  path: '/insight-studio/$insightId',
  getParentRoute: () => rootRoute,
} as any)

const GuestFeedRoute = GuestFeedImport.update({
  id: '/guest/feed',
  path: '/guest/feed',
  getParentRoute: () => rootRoute,
} as any)

const KnowledgeGraphGraphTypeDocumentidRoute =
  KnowledgeGraphGraphTypeDocumentidImport.update({
    id: '/knowledge-graph/$graphType/$documentid',
    path: '/knowledge-graph/$graphType/$documentid',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedImport
      parentRoute: typeof rootRoute
    }
    '/importer': {
      id: '/importer'
      path: '/importer'
      fullPath: '/importer'
      preLoaderRoute: typeof ImporterImport
      parentRoute: typeof rootRoute
    }
    '/guest/feed': {
      id: '/guest/feed'
      path: '/guest/feed'
      fullPath: '/guest/feed'
      preLoaderRoute: typeof GuestFeedImport
      parentRoute: typeof rootRoute
    }
    '/insight-studio/$insightId': {
      id: '/insight-studio/$insightId'
      path: '/insight-studio/$insightId'
      fullPath: '/insight-studio/$insightId'
      preLoaderRoute: typeof InsightStudioInsightIdImport
      parentRoute: typeof rootRoute
    }
    '/insight/$insightId': {
      id: '/insight/$insightId'
      path: '/insight/$insightId'
      fullPath: '/insight/$insightId'
      preLoaderRoute: typeof InsightInsightIdImport
      parentRoute: typeof rootRoute
    }
    '/news-feed/$documentid': {
      id: '/news-feed/$documentid'
      path: '/news-feed/$documentid'
      fullPath: '/news-feed/$documentid'
      preLoaderRoute: typeof NewsFeedDocumentidImport
      parentRoute: typeof rootRoute
    }
    '/insight-studio/': {
      id: '/insight-studio/'
      path: '/insight-studio'
      fullPath: '/insight-studio'
      preLoaderRoute: typeof InsightStudioIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledge-graph/': {
      id: '/knowledge-graph/'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphIndexImport
      parentRoute: typeof rootRoute
    }
    '/news-feed/': {
      id: '/news-feed/'
      path: '/news-feed'
      fullPath: '/news-feed'
      preLoaderRoute: typeof NewsFeedIndexImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexImport
      parentRoute: typeof rootRoute
    }
    '/knowledge-graph/$graphType/$documentid': {
      id: '/knowledge-graph/$graphType/$documentid'
      path: '/knowledge-graph/$graphType/$documentid'
      fullPath: '/knowledge-graph/$graphType/$documentid'
      preLoaderRoute: typeof KnowledgeGraphGraphTypeDocumentidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/importer': typeof ImporterRoute
  '/guest/feed': typeof GuestFeedRoute
  '/insight-studio/$insightId': typeof InsightStudioInsightIdRoute
  '/insight/$insightId': typeof InsightInsightIdRoute
  '/news-feed/$documentid': typeof NewsFeedDocumentidRoute
  '/insight-studio': typeof InsightStudioIndexRoute
  '/knowledge-graph': typeof KnowledgeGraphIndexRoute
  '/news-feed': typeof NewsFeedIndexRoute
  '/search': typeof SearchIndexRoute
  '/knowledge-graph/$graphType/$documentid': typeof KnowledgeGraphGraphTypeDocumentidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/importer': typeof ImporterRoute
  '/guest/feed': typeof GuestFeedRoute
  '/insight-studio/$insightId': typeof InsightStudioInsightIdRoute
  '/insight/$insightId': typeof InsightInsightIdRoute
  '/news-feed/$documentid': typeof NewsFeedDocumentidRoute
  '/insight-studio': typeof InsightStudioIndexRoute
  '/knowledge-graph': typeof KnowledgeGraphIndexRoute
  '/news-feed': typeof NewsFeedIndexRoute
  '/search': typeof SearchIndexRoute
  '/knowledge-graph/$graphType/$documentid': typeof KnowledgeGraphGraphTypeDocumentidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/importer': typeof ImporterRoute
  '/guest/feed': typeof GuestFeedRoute
  '/insight-studio/$insightId': typeof InsightStudioInsightIdRoute
  '/insight/$insightId': typeof InsightInsightIdRoute
  '/news-feed/$documentid': typeof NewsFeedDocumentidRoute
  '/insight-studio/': typeof InsightStudioIndexRoute
  '/knowledge-graph/': typeof KnowledgeGraphIndexRoute
  '/news-feed/': typeof NewsFeedIndexRoute
  '/search/': typeof SearchIndexRoute
  '/knowledge-graph/$graphType/$documentid': typeof KnowledgeGraphGraphTypeDocumentidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/importer'
    | '/guest/feed'
    | '/insight-studio/$insightId'
    | '/insight/$insightId'
    | '/news-feed/$documentid'
    | '/insight-studio'
    | '/knowledge-graph'
    | '/news-feed'
    | '/search'
    | '/knowledge-graph/$graphType/$documentid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/importer'
    | '/guest/feed'
    | '/insight-studio/$insightId'
    | '/insight/$insightId'
    | '/news-feed/$documentid'
    | '/insight-studio'
    | '/knowledge-graph'
    | '/news-feed'
    | '/search'
    | '/knowledge-graph/$graphType/$documentid'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/importer'
    | '/guest/feed'
    | '/insight-studio/$insightId'
    | '/insight/$insightId'
    | '/news-feed/$documentid'
    | '/insight-studio/'
    | '/knowledge-graph/'
    | '/news-feed/'
    | '/search/'
    | '/knowledge-graph/$graphType/$documentid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  ImporterRoute: typeof ImporterRoute
  GuestFeedRoute: typeof GuestFeedRoute
  InsightStudioInsightIdRoute: typeof InsightStudioInsightIdRoute
  InsightInsightIdRoute: typeof InsightInsightIdRoute
  NewsFeedDocumentidRoute: typeof NewsFeedDocumentidRoute
  InsightStudioIndexRoute: typeof InsightStudioIndexRoute
  KnowledgeGraphIndexRoute: typeof KnowledgeGraphIndexRoute
  NewsFeedIndexRoute: typeof NewsFeedIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  KnowledgeGraphGraphTypeDocumentidRoute: typeof KnowledgeGraphGraphTypeDocumentidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  ImporterRoute: ImporterRoute,
  GuestFeedRoute: GuestFeedRoute,
  InsightStudioInsightIdRoute: InsightStudioInsightIdRoute,
  InsightInsightIdRoute: InsightInsightIdRoute,
  NewsFeedDocumentidRoute: NewsFeedDocumentidRoute,
  InsightStudioIndexRoute: InsightStudioIndexRoute,
  KnowledgeGraphIndexRoute: KnowledgeGraphIndexRoute,
  NewsFeedIndexRoute: NewsFeedIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  KnowledgeGraphGraphTypeDocumentidRoute:
    KnowledgeGraphGraphTypeDocumentidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/feed",
        "/importer",
        "/guest/feed",
        "/insight-studio/$insightId",
        "/insight/$insightId",
        "/news-feed/$documentid",
        "/insight-studio/",
        "/knowledge-graph/",
        "/news-feed/",
        "/search/",
        "/knowledge-graph/$graphType/$documentid"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/feed": {
      "filePath": "feed.tsx"
    },
    "/importer": {
      "filePath": "importer.tsx"
    },
    "/guest/feed": {
      "filePath": "guest.feed.tsx"
    },
    "/insight-studio/$insightId": {
      "filePath": "insight-studio.$insightId.tsx"
    },
    "/insight/$insightId": {
      "filePath": "insight.$insightId.tsx"
    },
    "/news-feed/$documentid": {
      "filePath": "news-feed.$documentid.tsx"
    },
    "/insight-studio/": {
      "filePath": "insight-studio.index.tsx"
    },
    "/knowledge-graph/": {
      "filePath": "knowledge-graph.index.tsx"
    },
    "/news-feed/": {
      "filePath": "news-feed.index.tsx"
    },
    "/search/": {
      "filePath": "search.index.tsx"
    },
    "/knowledge-graph/$graphType/$documentid": {
      "filePath": "knowledge-graph.$graphType.$documentid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
